kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "youtrack.fullname" . }}-data
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.data.storageClass | quote }}
spec:
{{- with .Values.persistence.data.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.storageSize | quote }}
