kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "youtrack.fullname" . }}-backups
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.backups.storageClass | quote }}
spec:
{{- with .Values.persistence.backups.accessModes }}
  accessModes: {{ toYaml . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.storageSize | quote }}
