kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "youtrack.fullname" . }}-conf
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.conf.storageClass | quote }}
spec:
{{- with .Values.persistence.conf.accessModes }}
  accessModes: {{ toYaml . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.conf.storageSize | quote }}
