apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teamcity.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (include "teamcity.fullname" .) }}-data
        - name: artifacts
          persistentVolumeClaim:
            claimName: {{ default (include "teamcity.fullname" .) }}-artifacts
        - name: logs
          persistentVolumeClaim:
            claimName: {{ default (include "teamcity.fullname" .) }}-logs
        - name: temp
          emptyDir: {}
      serviceAccountName: {{ include "teamcity.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.volumePermissions.enabled }}
      initContainers:
        - name: init-chown-data
          image: "{{ .Values.volumePermissions.image.image }}:{{ .Values.volumePermissions.image.imageTag }}"
          imagePullPolicy: "{{ .Values.volumePermissions.image.pullPolicy }}"
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
          command:
            - sh
            - -c
            - |
              chown -Rv {{ .Values.agent.securityContext.runAsUser }}:{{ .Values.agent.securityContext.runAsGroup }} /data
          volumeMounts:
            - name: data
              mountPath: /data
            - name: artifacts
              mountPath: /data/system/artifacts
          securityContext:
            runAsUser: {{ .Values.volumePermissions.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: logs
              mountPath: /opt/teamcity/logs
            - name: temp
              mountPath: /opt/teamcity/temp
            - name:  data
              mountPath: /data/teamcity_server/datadir
            - name: artifacts
              mountPath: /data/teamcity_server/datadir/system/artifacts
          ports:
            - name: http
              containerPort: 8111
              protocol: TCP
        {{- with .Values.env }}
          env:
{{ toYaml . | indent 12 }}
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
